### ISSUE TITLE
UWSGI server returns status 400 with traceback 

### ISSUE THREAD

**Issue by pushkalkatara** [Vernacular-ai/dialogy-template-simple-transformers#5]
Issue while testing through UWSGI server:
```
root@e2e-81-69:~/pushkal/test/tests# python test_test.py 
{"cause":"Traceback (most recent call last):\n  File \"./test/src/api/endpoints.py\", line 82, in slu\n    response = PREDICT_API(sentences, context, intents_info=intents_info)\nTypeError: predict() got an unexpected keyword argument 'intents_info'\n","message":"predict() got an unexpected keyword argument 'intents_info'"}
```

Possible Fix:
In endpoints.py line 82
```
response = PREDICT_API(sentences, context, intents_info=intents_info)
```

to 
```
response = PREDICT_API(sentences, context)
```

as predict() currently doesnt take intents_info as the argument.

**Comment by ltbringer** [comment]
@pushkalkatara I would say this would be a better way to handle it:

Within your `[[python_package_import_name]]/src/controller/prediction.py`, 

```python
# This function should also receive those arguments.
def predict(utterance: List[str], context: Dict[str, Any], reference_time: Optional[int] = None):
    ...
```

https://github.com/Vernacular-ai/dialogy-template-simple-transformers/blob/774c237b04fbd7bd158c83567b9a3da4f3f7fbd5/project/%5B%5Bpython_package_import_name%5D%5D/src/controller/prediction.py.jinja#L94
